[tool.black]
line-length = 88
target-version = ['py37', 'py38']

[tool.isort]
line_length = 88
profile = "black"

[tool.pytest.ini_options]
minversion = 6.0
python_files = "tests/*.py"
python_functions = "test_*"
